#ifndef NETWORKCONSTANTS_H
#define NETWORKCONSTANTS_H

// Network protocol version
#define NETWORK_PROTOCOL_VERSION 1

// Size limits
#define MAX_USERNAME_LENGTH 32
#define MAX_PASSWORD_LENGTH 64
#define MAX_EMAIL_LENGTH 64
#define MAX_CHANNEL_NAME_LENGTH 32
#define MAX_CATEGORY_NAME_LENGTH 32
#define MAX_STATUS_LENGTH 128
#define MAX_FILE_NAME_LENGTH 256
#define MAX_FILE_SIZE (100 * 1024 * 1024)  // 100MB
#define MAX_VOICE_PACKET_SIZE (32 * 1024)   // 32KB
#define MAX_VIDEO_PACKET_SIZE (256 * 1024)  // 256KB

// Timeouts (in milliseconds)
#define CONNECTION_TIMEOUT 30000
#define RESPONSE_TIMEOUT 5000
#define HEARTBEAT_TIMEOUT 45000
#define FILE_TRANSFER_TIMEOUT 60000

// Rate limiting
#define MAX_MESSAGES_PER_SECOND 10
#define MAX_FILE_TRANSFERS_PER_MINUTE 5
#define MAX_VOICE_BITRATE 64000    // 64 Kbps
#define MAX_VIDEO_BITRATE 512000   // 512 Kbps

#endif 